Console.WriteLine("want to say hello");
Console.WriteLine("Hello World!");
Console.WriteLine("Hello Kate!");
Console.WriteLine("Hello World!");
Console.WriteLine("Just hello");
Console.WriteLine("Hello, Git!");
Console.WriteLine("Hello, Git!");
Console.WriteLine("Hello, Git!");
Console.WriteLine("Hello, Git!");
Console.WriteLine("Hello, Git!");
Console.WriteLine("Hello, Git!");